# Project-wide Gradle settings.
# systemProp.ANDROID_USER_HOME=C:/android_home
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
hermesEnabled=true
edgeToEdgeEnabled=true
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false
compileSdkVersion=36
targetSdkVersion=35
buildToolsVersion=35.0.0
minSdkVersion=24
ndkVersion=28.2.13676358
expo.inlineModules.watchedDirectories=[]
